// Generated by scripts/import-illustrations.mjs. Do not edit by hand.
//
// Illustrations from African Storybook, reused under CC BY 4.0. Per-album
// author, translator and illustrator credits live in data/stories.ts and are
// shown in the reader's info sheet.
//
// Each array is aligned with the matching album in data/asbLongReadingPages.ts:
// index N is the illustration for page N, and `undefined` marks a page the
// album leaves unillustrated.
//
// Aspect ratios are read from the files themselves: the albums mix square and
// landscape artwork, so a single ratio would stretch part of the catalogue.
import type { ImageSourcePropType } from "react-native";

export type StoryIllustration = {
  source: ImageSourcePropType;
  aspectRatio: number;
};

export const asbLongReadingImages: Record<
  string,
  readonly (StoryIllustration | undefined)[]
> = {
  melokuhleDay: [
    undefined,
    {
      source: require("../assets/illustrations/melokuhleDay/page-02.webp"),
      aspectRatio: 1.0000,
    },
    undefined,
    {
      source: require("../assets/illustrations/melokuhleDay/page-04.webp"),
      aspectRatio: 1.0000,
    },
    undefined,
    {
      source: require("../assets/illustrations/melokuhleDay/page-06.webp"),
      aspectRatio: 1.0000,
    },
    undefined,
    {
      source: require("../assets/illustrations/melokuhleDay/page-08.webp"),
      aspectRatio: 1.0000,
    },
    undefined,
    {
      source: require("../assets/illustrations/melokuhleDay/page-10.webp"),
      aspectRatio: 1.0000,
    },
    undefined,
    {
      source: require("../assets/illustrations/melokuhleDay/page-12.webp"),
      aspectRatio: 1.0000,
    },
    undefined,
    {
      source: require("../assets/illustrations/melokuhleDay/page-14.webp"),
      aspectRatio: 1.0000,
    },
    undefined,
    {
      source: require("../assets/illustrations/melokuhleDay/page-16.webp"),
      aspectRatio: 1.0000,
    },
  ],
  blueBus: [
    {
      source: require("../assets/illustrations/blueBus/page-01.webp"),
      aspectRatio: 1.2527,
    },
    {
      source: require("../assets/illustrations/blueBus/page-02.webp"),
      aspectRatio: 1.4029,
    },
    {
      source: require("../assets/illustrations/blueBus/page-03.webp"),
      aspectRatio: 1.1978,
    },
    {
      source: require("../assets/illustrations/blueBus/page-04.webp"),
      aspectRatio: 1.1282,
    },
    {
      source: require("../assets/illustrations/blueBus/page-05.webp"),
      aspectRatio: 1.2619,
    },
    {
      source: require("../assets/illustrations/blueBus/page-06.webp"),
      aspectRatio: 1.3297,
    },
    {
      source: require("../assets/illustrations/blueBus/page-07.webp"),
      aspectRatio: 1.1722,
    },
    {
      source: require("../assets/illustrations/blueBus/page-08.webp"),
      aspectRatio: 1.2729,
    },
    {
      source: require("../assets/illustrations/blueBus/page-09.webp"),
      aspectRatio: 1.2619,
    },
    {
      source: require("../assets/illustrations/blueBus/page-10.webp"),
      aspectRatio: 1.1630,
    },
    {
      source: require("../assets/illustrations/blueBus/page-11.webp"),
      aspectRatio: 1.0824,
    },
    {
      source: require("../assets/illustrations/blueBus/page-12.webp"),
      aspectRatio: 1.1996,
    },
    {
      source: require("../assets/illustrations/blueBus/page-13.webp"),
      aspectRatio: 1.2875,
    },
    {
      source: require("../assets/illustrations/blueBus/page-14.webp"),
      aspectRatio: 1.1429,
    },
    {
      source: require("../assets/illustrations/blueBus/page-15.webp"),
      aspectRatio: 1.2601,
    },
    {
      source: require("../assets/illustrations/blueBus/page-16.webp"),
      aspectRatio: 1.2344,
    },
  ],
  pickItUp: [
    {
      source: require("../assets/illustrations/pickItUp/page-01.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/pickItUp/page-02.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/pickItUp/page-03.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/pickItUp/page-04.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/pickItUp/page-05.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/pickItUp/page-06.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/pickItUp/page-07.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/pickItUp/page-08.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/pickItUp/page-09.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/pickItUp/page-10.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/pickItUp/page-11.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/pickItUp/page-12.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/pickItUp/page-13.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/pickItUp/page-14.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/pickItUp/page-15.webp"),
      aspectRatio: 1.0000,
    },
    undefined,
  ],
  shareFairly: [
    {
      source: require("../assets/illustrations/shareFairly/page-01.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/shareFairly/page-02.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/shareFairly/page-03.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/shareFairly/page-04.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/shareFairly/page-05.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/shareFairly/page-06.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/shareFairly/page-07.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/shareFairly/page-08.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/shareFairly/page-09.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/shareFairly/page-10.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/shareFairly/page-11.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/shareFairly/page-12.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/shareFairly/page-13.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/shareFairly/page-14.webp"),
      aspectRatio: 0.9835,
    },
    {
      source: require("../assets/illustrations/shareFairly/page-15.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/shareFairly/page-16.webp"),
      aspectRatio: 1.0000,
    },
  ],
  simbegwire: [
    {
      source: require("../assets/illustrations/simbegwire/page-01.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/simbegwire/page-02.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/simbegwire/page-03.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/simbegwire/page-04.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/simbegwire/page-05.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/simbegwire/page-06.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/simbegwire/page-07.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/simbegwire/page-08.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/simbegwire/page-09.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/simbegwire/page-10.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/simbegwire/page-11.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/simbegwire/page-12.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/simbegwire/page-13.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/simbegwire/page-14.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/simbegwire/page-15.webp"),
      aspectRatio: 0.7857,
    },
    {
      source: require("../assets/illustrations/simbegwire/page-16.webp"),
      aspectRatio: 1.0000,
    },
  ],
  rainbowTale: [
    {
      source: require("../assets/illustrations/rainbowTale/page-01.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/rainbowTale/page-02.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/rainbowTale/page-03.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/rainbowTale/page-04.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/rainbowTale/page-05.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/rainbowTale/page-06.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/rainbowTale/page-07.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/rainbowTale/page-08.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/rainbowTale/page-09.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/rainbowTale/page-10.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/rainbowTale/page-11.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/rainbowTale/page-12.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/rainbowTale/page-13.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/rainbowTale/page-14.webp"),
      aspectRatio: 1.0000,
    },
  ],
  mousePrince: [
    {
      source: require("../assets/illustrations/mousePrince/page-01.webp"),
      aspectRatio: 1.0073,
    },
    {
      source: require("../assets/illustrations/mousePrince/page-02.webp"),
      aspectRatio: 1.0073,
    },
    {
      source: require("../assets/illustrations/mousePrince/page-03.webp"),
      aspectRatio: 1.0073,
    },
    {
      source: require("../assets/illustrations/mousePrince/page-04.webp"),
      aspectRatio: 1.0110,
    },
    {
      source: require("../assets/illustrations/mousePrince/page-05.webp"),
      aspectRatio: 1.0110,
    },
    {
      source: require("../assets/illustrations/mousePrince/page-06.webp"),
      aspectRatio: 1.0092,
    },
    {
      source: require("../assets/illustrations/mousePrince/page-07.webp"),
      aspectRatio: 1.0092,
    },
    {
      source: require("../assets/illustrations/mousePrince/page-08.webp"),
      aspectRatio: 1.0092,
    },
    {
      source: require("../assets/illustrations/mousePrince/page-09.webp"),
      aspectRatio: 1.0110,
    },
    {
      source: require("../assets/illustrations/mousePrince/page-10.webp"),
      aspectRatio: 1.0110,
    },
    {
      source: require("../assets/illustrations/mousePrince/page-11.webp"),
      aspectRatio: 1.0110,
    },
    {
      source: require("../assets/illustrations/mousePrince/page-12.webp"),
      aspectRatio: 1.0092,
    },
    {
      source: require("../assets/illustrations/mousePrince/page-13.webp"),
      aspectRatio: 1.0073,
    },
    {
      source: require("../assets/illustrations/mousePrince/page-14.webp"),
      aspectRatio: 1.0092,
    },
    {
      source: require("../assets/illustrations/mousePrince/page-15.webp"),
      aspectRatio: 1.0018,
    },
    {
      source: require("../assets/illustrations/mousePrince/page-16.webp"),
      aspectRatio: 1.0018,
    },
  ],
  birdKing: [
    {
      source: require("../assets/illustrations/birdKing/page-01.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/birdKing/page-02.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/birdKing/page-03.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/birdKing/page-04.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/birdKing/page-05.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/birdKing/page-06.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/birdKing/page-07.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/birdKing/page-08.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/birdKing/page-09.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/birdKing/page-10.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/birdKing/page-11.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/birdKing/page-12.webp"),
      aspectRatio: 1.0000,
    },
  ],
  crowdedHouse: [
    {
      source: require("../assets/illustrations/crowdedHouse/page-01.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/crowdedHouse/page-02.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/crowdedHouse/page-03.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/crowdedHouse/page-04.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/crowdedHouse/page-05.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/crowdedHouse/page-06.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/crowdedHouse/page-07.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/crowdedHouse/page-08.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/crowdedHouse/page-09.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/crowdedHouse/page-10.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/crowdedHouse/page-11.webp"),
      aspectRatio: 0.9212,
    },
    {
      source: require("../assets/illustrations/crowdedHouse/page-12.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/crowdedHouse/page-13.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/crowdedHouse/page-14.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/crowdedHouse/page-15.webp"),
      aspectRatio: 1.0000,
    },
    {
      source: require("../assets/illustrations/crowdedHouse/page-16.webp"),
      aspectRatio: 1.0000,
    },
  ],
};
